### ISSUE TITLE
Test of DestinationSideOfPier fails in southern hemisphere

### ISSUE THREAD

**Issue by filippo-riccio** [ASCOMInitiative/Conform#1]
Hi,

DestinationSideOfPier is tested with target coordinates at declination +45°, which is under the horizon when the site latitude is < -45°. In this situation Conform reports an error since the driver returns "pierUnknown".

Regards,

Filippo Riccio

**Comment by Peter-Simpson** [comment]
Hi Filippo,

I'm guessing that this is the 10Micron driver - I have a GM2000HPS myself so recognise your name from the 10Micron support forum. :smiley: 

That does sound like an issue to me, thanks for reporting  it. I'll revise the selection of declination to make the test compatible with southern hemisphere coordinates.

Regards, Peter

**Comment by Peter-Simpson** [comment]
Hi Filippo,

I've found and fixed the issue, here is a link to a new installer for [Conform 6.4.63.0](http://download.ascom-standards.org/beta/Conform(6.4.63.0)setup.exe). Please let me know whether this fixes the issue. If it does I'll post the new version as a formal GitHub release.

If the issue remains, please turn debug on on the Conform Options menu, run the test again and post the full log file.

Thanks, Peter

**Comment by filippo-riccio** [comment]
It works! Thank you and see you on the 10micron forum :smiley: 

Regards,
    Filippo

**Comment by Peter-Simpson** [comment]
Thanks Filippo, I'm glad it worked! I've now created a release for the new version; you don't need to download it because it's identical to the version you already have.

Regards, Peter
