### ISSUE TITLE
Conform return error if calibratoron on not return ready 

### ISSUE THREAD

**Issue by skybadger** [ASCOMInitiative/Conform#8]
For Conform 6.5.7500.22515. 

The ASCOM Windows API reference for covercalibrator says this :  (same for both off and on) 
This is a mandatory method for a calibrator device.
If the calibrator requires time to safely stabilise after use, CalibratorState must return NotReady. When the calibrator is safely off CalibratorState must return Off.
For devices with both cover and calibrator capabilities, this method will return the CoverState to its status prior to calling CalibratorOn(Int32).
If an error condition arises while turning off the calibrator, CalibratorState must be set to Error rather than Unknown.

The conform call returns this : 
18:32:39.900 CalibratorOn                               About to call CalibratorOn method with brightness: 1023
18:32:40.452 CalibratorOn                      ERROR    CalibratorOn with brightness 1023 was unsuccessful - the returned CalibratorState was 'NotReady' instead of 'Ready'. The synchronous operation took 0.6 seconds

The Alpaca documentation says not a lot other than provide a brightness. 
I suggest the conform call has to poll for the calibrator state going to ready . It doesn't know what the acceptable timescale maybe if its a lamp needing to warm up..

**Comment by Peter-Simpson** [comment]
This turned out to be a device issue as documented [here](https://ascomtalk.groups.io/g/Developer/topic/87838750).  Conform will be updated to include more comprehensive messaging indicating that the error can also arise when the status property is not set before the Alpaca device returns control the originator.
